# Copyright 2025 NVIDIA CORPORATION & AFFILIATES
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: specx-config
  namespace: nvidia-network-operator
data:
  config: |
    {
      "spectrum-x-networks": {
        "cross_rail_subnet": "192.0.0.0/8",
        "mtu": 9000,
        "rails": [
          {
            "name": "rail-1",
            "subnet": "192.0.0.0/11"
          },
          {
            "name": "rail-2",
            "subnet": "192.32.0.0/11"
          }
        ]
      },
      "rail_device_mapping": [
        {
          "rail_name": "rail-1",
          "dev_name": "eth0"
        },
        {
          "rail_name": "rail-2",
          "dev_name": "eth1"
        }
      ],
      "hosts": [
        {
          "host_id": "host-1",
          "rails": [
            {
              "name": "rail-1",
              "network": "192.0.0.0/31",
              "peer_leaf_port_ip": "172.0.0.0"
            },
            {
              "name": "rail-2",
              "network": "192.32.0.0/31",
              "peer_leaf_port_ip": "172.32.0.0"
            }
          ]
        },
        {
          "host_id": "host-2",
          "rails": [
            {
              "name": "rail-1",
              "network": "192.0.0.2/31",
              "peer_leaf_port_ip": "172.0.0.2"
            },
            {
              "name": "rail-2",
              "network": "192.32.0.2/31",
              "peer_leaf_port_ip": "172.32.0.2"
            }
          ]
        }
      ]
    }
