# permissions for end users to view spectrumxconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spectrum-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: spectrumxconfig-viewer-role
rules:
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxconfigs/status
  verbs:
  - get
