# Adds namespace to all resources.
namespace: nvidia-network-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: spectrum-x-operator-

# Labels to add to all resources and selectors.
#labels:
#- includeSelectors: true
#  pairs:
#    someName: someValue

resources:
- ../rbac
- ../manager
- ../flowcontroller
- role.yaml
- role_binding.yaml
