---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flowcontroller
  namespace: system
  labels:
    control-plane: flowcontroller
    app.kubernetes.io/name: spectrum-x-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: flowcontroller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: flowcontroller
      labels:
        control-plane: flowcontroller
    spec:
      hostNetwork: true
      securityContext:
        runAsNonRoot: false
      initContainers:
        - name: copy-rail-cni
          image: controller:latest
          command: ["cp", "/railcni", "/hostcni/rail"]
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              drop:
              - "ALL"
          volumeMounts:
          - name: host-cni
            mountPath: /hostcni
      containers:
      - command:
        - /flowcontroller
        - --metrics-bind-address=0
        - --health-probe-bind-address=0
        image: controller:latest
        name: flowcontroller
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            drop:
            - "ALL"
        volumeMounts:
        - name: proc
          mountPath: /proc
        - name: sys
          mountPath: /sys
        - name: ovs
          mountPath: /var/run/openvswitch/
        - name: ovs-systemd-config
          mountPath: /etc/default/openvswitch-switch
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: ovs
        hostPath:
          path: /var/run/openvswitch
      - name: ovs-systemd-config
        hostPath:
          path: /etc/default/openvswitch-switch
      - name: host-cni
        hostPath:
          path: /opt/cni/bin
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
